paths:
    migrations: '%%PHINX_CONFIG_DIR%%/glued/Core/Install/Migrations'
    seeds: '%%PHINX_CONFIG_DIR%%/glued/Core/Install/Seeds'

foreign_keys: true

environments:
    default_migration_table: phinxlog
    default_database: production
    production:
        adapter: mysql
        host: '%%PHINX_DBHOST%%'
        name: '%%PHINX_DBNAME%%'
        user: '%%PHINX_DBUSER%%'
        pass: '%%PHINX_DBPASS%%'
        port: '%%PHINX_DBPORT%%'
        charset: utf8

version_order: creation
