name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - uses: nanasess/setup-php@v3.0.6
      with:
        php-version: '7.4'
    - uses: haltuf/mysql-action 
      with:
        mysql user: 'glued' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: 'glued' # Required if "mysql user" exists. The password for the "mysql user"
        authentication plugin: 'mysql_old_password'  
        mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
        mysql database: 'glued' # Optional, default value is "test". The specified database which will be create
    - name: Validate composer.json and composer.lock
      env:
        GLUED_IN_DOCKER: true
      run: composer validate

    # TODO look into rewriting composer.json so that phinx migrations
    # and other postinstall magic don't interfere with the code below
    #
    - name: Install dependencies
      env:
        GLUED_IN_DOCKER: true
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
