name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - uses: nanasess/setup-php@v3.0.6
      with:
        php-version: '7.4'

    - name: Validate composer.json and composer.lock
      env:
        GLUED_IN_DOCKER: true
      run: composer validate

    # TODO look into rewriting composer.json so that phinx migrations
    # and other postinstall magic don't interfere with the code below
    #
    - name: Install dependencies
      env:
        GLUED_IN_DOCKER: true
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
